# Generated by Django 4.0 on 2022-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_adminvacantion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminvacantion',
            name='at_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
