# Generated by Django 4.0 on 2022-01-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_adminvacantion_at_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrezervation',
            name='server_anounced',
        ),
        migrations.AlterField(
            model_name='clientrezervation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
